spring:
  application:
    name: estudify

  main:
    web-application-type: reactive

  datasource:
    url: "jdbc:mysql://66.94.122.246:3306/studify?allowPublicKeyRetrieval=true&parseTime=true&loc=Local"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:Playhack1.}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: HikariPool-1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  codec:
    max-in-memory-size: 10MB

studify:
  content:
    concurrency: 21
stripe:
  secret-key: sk_test_51RxA6wE3ZKBHarUm7IPVUwvE4wbV1TbucdFzNgKIgV0zjx8cpqjmrw0q9xy5VBc7fr90Ij2YAC4rveWypngQA0zK00IMkUBACx
  webhook-secret: whsec_f39ebfe2c72303d9a71abe4dfe7696936537fc982be0aa8945298f86022db790
app:
  frontendOrigin: https://seu-dominio.com

gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: AIzaSyAht6-QjFO4mNXb_n6ha89zsRa6GCYIP2M

logging:
  level:
    reactor.netty: WARN
    org.springframework.web.reactive.function.client.ExchangeFunctions: WARN
